module.exports = {
  app: require(`./src/app`), // whatever your route file is
  collection: `gss`, // what you want to name this in postman
  workspaceId: ``, // workspace id generated by postman,
  postmanKey: `` // private api key provided by postman
};
